name: comparador_ra
description: Comparador de precios con RA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  go_router: ^13.0.0

 # Scanner avanzado
  mobile_scanner: ^5.0.0
  image_picker: ^1.0.7
  
  # NUEVAS para IA
  http: ^1.2.0          # Para enviar imagen
  # Efectos y feedback
  vibration: ^3.1.4
  flutter_animate: ^4.5.0

  url_launcher: ^6.2.5
  
  # Permisos
  permission_handler: ^11.3.0
  
  # Local storage avanzado
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0 
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
